# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - "*"

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Debug"

stages:
  - stage: BuildDLLs
    jobs:
      - job:
        steps:
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: "$(solution)"

          - script: |
              dotnet build --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"
            displayName: "dotnet build"

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: framework
