# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- "*"

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1
– task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
- script: |
    set SecretKey="Secret key from environment"
    set TransientFaultHandlingOptions__Enabled="true"
    set TransientFaultHandlingOptions__AutoRetryDelay="00:00:13"
– task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **\\tests-unit.dll
      !**\*TestAdapter.dll
      !**\obj\**
      !**\bin\**\ref\**
# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    #testResultsFormat: 'NUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/*.trx' 
    searchFolder: '$(Agent.TempDirectory)/TestResults' # Optional
    #mergeTestResults: false # Optional
    failTaskOnFailedTests: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional